import { useEffect, useState } from "react";
import axios from "axios";
import { Link, useNavigate } from "react-router-dom";
import { useCartStore, useOrderStore } from "../other/product";
import Slider from "../components/slider.jsx";
import "./checkOut.css";

const CheckOut = () => {
    const navigate = useNavigate();
    const {createOrder} = useOrderStore();
    const { cart, incrementQuantity, decrementQuantity } = useCartStore();
    const totalPrice = cart.reduce((total, item) => total + (item.price*item.quantity), 0);
    const [related, setRelated] = useState([]);
    useEffect(() => {
        const fetchRelated = async () => {
            try {
                const randRes = await axios.get("/api/products/random");
                if (!randRes.data || randRes.data.length === 0) return;
                const randomProduct = randRes.data[0];
                const res = await axios.get(`/api/products/${randomProduct._id}/related`);
                setRelated(res.data);
            } catch (error) {
                console.error("Failed to fetch related products", error);
            }
        };
        fetchRelated();
    }, []);

    const orderItem = async () => {
        alert("product not valid!");
        // const { success, message } = await createOrder(cart);
        // (!success)?setMassage(message):setMassage(message)
    };
    return(
        <div className="checkoutPage">
            <div className="CheckoutNav">
                <Link to="/"><h3>Home</h3></Link>
                <center><h2>Place Order.</h2> </center>
            </div>
            <div className="orderFromCover">
                <div className="orderForm">
                    <input id="fName" type="text" placeholder="Full Name" />
                    <input id="email" autoComplete="email" type="email" placeholder="example@gmail.com" />
                    <input id="phone" autoComplete="tel" type="tel" placeholder="9800000000" />
                    <input id="deliveryNotes" type="text" placeholder="Delevery notes" />
                    <div style={{display:"flex",flexDirection:"column",alignItems:"flex-start"}}>Delevery Address
                        <input id="address" autoComplete="address-line1" type="text" placeholder="Address: kathmandu tirpurashor" />
                        <input id="street" type="text" placeholder="Street name, location/landmark" />
                    </div>
                    <p> Paynment Methods:</p>
                    <div className="payMethod"> 
                        <span>
                            <input type="radio" name="payment-methods" value={'cashOnDelevery'} id="cashOnDelevery"/>
                            <label htmlFor="cashOnDelevery">Cash-On-Delevery</label>
                        </span>
                        <span>
                            <input type="radio" name="payment-methods" value={'QRPaynment'} id="QRPaynment"/>
                            <label htmlFor="QRPaynment">QR-Paynment</label>
                            {/* create popover to show qr paynment with qr which is generated by backend and also show the qr code in the popover */}
                        </span>
                    </div>
                    {cart.length === 0 ?null:(<button className="OrderConfirmBtn" onClick={orderItem}>place order</button>)}
                </div>
                <div className="orderItems">
                    {cart.length === 0 ? (<p>Your cart is empty</p>) : (cart.map((item,index) => (
                        <li key={index} className="cartItems">
                            <img 
                                src={item.file|| 'icon.svg'}
                                className="cartItemImage"
                                onClick={()=>navigate(`/product/${item.id}`)}
                            />
                            <div className="cartItemDetails">
                                <p title={item.name} className="productName">{item.name}</p>
                                <div>
                                    <span className="price">@: {item.price} / Rs: {item.price*item.quantity}</span>
                                    <div className="qtyAlter">
                                        <button onClick={()=>incrementQuantity(item.id)}>+</button>
                                        <button>{item.quantity}</button>
                                        <button 
                                            style={{color:item.quantity===1?'red':'inherit'}}
                                            onClick={()=>decrementQuantity(item.id)}
                                        >{item.quantity===1?'x':'-'}</button>
                                    </div>
                                </div>
                            </div>
                        </li>
                    )))}
                    <p className="price checkOutPrice">Total Rs: {totalPrice}</p>
                </div>
            </div>
            <h4>Related products</h4>
            <Slider products={related}/>
        </div>
    )
}
export default CheckOut;